M48
; DRILL file {KiCad 9.0.4} date 2025-11-01T20:04:55+0100
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2025-11-01T20:04:55+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.4
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C1.100
%
G90
G05
T1
X5.391Y51.742
X5.391Y49.202
X245.92Y74.76
X245.92Y72.22
M30
